      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --fix-missing \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            libssl-dev \
            openssl \
            zlib1g-dev \
            libffi-dev \
            patch \
            autoconf \
            automake \
            libtool \
            pkg-config \
            cmake \
            zip \
            unzip
